public class switchc {
    public static void main(String[] args) {
        int a =10;
        int b = 34;

        switch (a) {
            case 1:
            System.out.println("samosa");
            System.out.println("burger");
            System.out.println("mango shake ");

        
                
                break;
        
            default:
            System.out.println("we realise we are deraming ");
                break;
        }
    }
    
}
